CREATE TABLE IF NOT EXISTS `users` (
	`id` INT(10) NOT NULL AUTO_INCREMENT,
	`username` VARCHAR(32) NOT NULL,
	`hash` VARCHAR(128) NOT NULL,
	PRIMARY KEY (`id`)
);

CREATE TABLE IF NOT EXISTS `history` (
	`id` INT(10) NOT NULL AUTO_INCREMENT,
	`user_id` INT(10) NOT NULL,
	`title` VARCHAR(50) NOT NULL,
	`key` VARCHAR(32) NOT NULL,
	`lang` VARCHAR(10),
	`code` TEXT NOT NULL,
	`pw` VARCHAR(32),
	`time` TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
	`pw_req` INT(1) DEFAULT '0',
	PRIMARY KEY (`id`),
	FOREIGN KEY (user_id) REFERENCES users (id)
)